config/routes.rb
ShelterExchangeApp::Application.routes.draw do

  # Shared Functions
  #----------------------------------------------------------------------------
  namespace :shared do

    # Shared :: Breeds
    #----------------------------------------------------------------------------
    resources :breeds, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end

    # Shared :: Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end
  end
  #----------------------------------------------------------------------------


  # Application - Routes for *subdomain*.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::App) do

    # Notes
    #----------------------------------------------------------------------------
    resources :notes, :only => [:show, :create, :edit, :update, :destroy] do
      resources :documents, :only => [:create, :destroy]
    end

    # Status Histories
    #----------------------------------------------------------------------------
    resources :status_histories, :only => [:edit, :update, :destroy] do
    end

    # Items
    #----------------------------------------------------------------------------
    resources :items

    # Reports
    #----------------------------------------------------------------------------
    resources :reports do
      collection do
        get :custom
        get :status_by_month_year
        get :type_by_month_year
      end
    end

    # Locations
    #----------------------------------------------------------------------------
    resources :locations, :only => [:create, :edit, :update, :destroy] do
      collection do
        get :find_all
      end
    end

    # Accommodations
    #----------------------------------------------------------------------------
    resources :accommodations, :except => [:show]

    # Tasks
    #----------------------------------------------------------------------------
    resources :tasks, :except => [:show] do
      post :complete, :on => :member
    end

    # Communities
    #----------------------------------------------------------------------------
    resources :communities do
      collection do
        get :filter_notes
        get :find_animals_in_bounds
        get :find_animals_for_shelter
      end
    end

    # Maps
    #----------------------------------------------------------------------------
    resources :maps, :only => [:overlay]

    # Contacts
    #----------------------------------------------------------------------------
    resources :contacts do
      resources :notes
      collection do
        get :filter_animals_by_status
        get :find_by_full_name
        post :export
        post :import
        post :import_mapping
      end
    end

    # Photos
    #----------------------------------------------------------------------------
    resources :photos, :only => [:destroy]

    # Documents
    #----------------------------------------------------------------------------
    resources :documents, :only => [:destroy]

    # Animals
    #----------------------------------------------------------------------------
    resources :animals do
      resources :notes
      resources :tasks
      resources :photos, :only => [:create, :destroy] do
        get :refresh_gallery, :on => :collection
      end

      member do
        match :print, :via => [:get, :post]
      end

      collection do
        get :filter_notes
        get :auto_complete
        post :export
      end
    end

    # Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:index, :edit, :update]

    # Wish Lists
    #----------------------------------------------------------------------------
    resources :wish_lists, :only => [:edit, :update]

    # Capacities
    #----------------------------------------------------------------------------
    resources :capacities

    # Account Settings
    #----------------------------------------------------------------------------
    resources :settings, :only => [:index]
    match '/settings/:tab' => 'settings#index', :as => :setting

    resources :token_authentications, :only => [:create, :destroy]

    # Data Export
    #----------------------------------------------------------------------------
    match '/data_exports/download' => 'data_exports#download', :as => :download_data_exports
    resources :data_exports, :only => [:create]

    # Integrations
    #----------------------------------------------------------------------------
    resources :integrations, :only => [:create, :destroy]


    # Announcements
    #----------------------------------------------------------------------------
    resources :announcements do
      post :hide, :on => :collection
    end

    # Users
    #----------------------------------------------------------------------------
    resources :users, :except => [:show, :new, :create] do
      member do
        put :change_password
        post :change_owner
        get :valid_token
      end
      post :invite, :on => :collection
    end


    devise_for :users,
               :path => "",
               :path_names => { :sign_in => "login", :sign_out => "logout",
                                :confirmation => "confirmation", :invitation => "invitation" }


    # Dashboard
    #----------------------------------------------------------------------------
    match "/dashboard", :to => 'dashboard#index'

    # ROOT
    #----------------------------------------------------------------------------
    root :to => redirect("/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------




  # Admin - Routes for manage.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Admin) do

    namespace :admin do

      # Admin :: Dashboard
      #----------------------------------------------------------------------------
      resources :dashboard, :only => [:index]

      # Admin :: Shelters
      #----------------------------------------------------------------------------
      resources :shelters, :only => [:index, :show, :edit, :update] do
        get :live_search, :on => :collection
      end

      # Admin :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Integrations
      #----------------------------------------------------------------------------
      resources :integrations, :only => [:index]

      # Admin :: Users
      #----------------------------------------------------------------------------
      resources :users, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Announcements
      #----------------------------------------------------------------------------
      resources :announcements, :except => [:new]

      # Admin :: Accounts
      #----------------------------------------------------------------------------
      resources :accounts, :only => [:edit, :update]

      # Admin :: Export
      #----------------------------------------------------------------------------
      resources :exports, :only => [:index]
      match "exports/:export_type" => "exports#show", :as => :export, :defaults => { :format => :csv }, :via => [:get]

      # Admin :: Reports
      #----------------------------------------------------------------------------
      resources :reports do
        collection do
          get :custom
          get :status_by_month_year
          get :type_by_month_year
        end
      end
    end

    # Admin :: Owners :: Devise
    #----------------------------------------------------------------------------
    match '/login' => redirect('/admin/login')
    devise_for :owners, :path => "admin", :controllers => { :sessions => "admin/owners/sessions" },
                        :path_names => { :sign_in => "login", :sign_out => "logout" }



    # Root
    #----------------------------------------------------------------------------
    root :to => redirect("/admin/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Api - Routes for api.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Api) do

    namespace :api, :path => "/", :defaults => { :version => "v1" } do

      # Api :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        collection do
          get :search
        end
      end

      match '/:version/animals' => 'animals#index', via: [:get, :options], :as => :list_animals
      match '/:version/animals/search' => 'animals#search', via: [:get, :options], :as => :search_animals
    end

  end


#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Public - Routes for www.shelterexchange.org or shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Public) do

    namespace :public, :path => "/" do

      # Public :: Save A Life
      #----------------------------------------------------------------------------
      resources :save_a_life do
        collection do
          get :find_animals_in_bounds
        end

app/models/note.rb
class Note < ActiveRecord::Base
  default_scope :order => 'notes.created_at DESC'

  # Constants
  #----------------------------------------------------------------------------
  DEFAULT_CATEGORY = "general"
  CATEGORIES = %w[general medical behavioral intake].freeze

  # Associations
  #----------------------------------------------------------------------------
  belongs_to :shelter, :readonly => true
  belongs_to :notable, :polymorphic => true

  has_many :documents, :as => :attachable, :dependent => :destroy

  # Validations
  #----------------------------------------------------------------------------
  validates :title, :presence => true
  validates :category, :inclusion => { :in => CATEGORIES, :message => "needs to be selected" }

  # Scopes
  #----------------------------------------------------------------------------
  scope :without_hidden, where(:hidden => false)

  # Instance Methods
  #----------------------------------------------------------------------------
  def notable?
    !!self.notable
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  respond_to :js

  def show
    @note = @current_shelter.notes.includes(:documents).find(params[:id])
  end

  def create
    @notable = find_polymorphic_class
    @note = @current_shelter.notes.new(params[:note].merge(:notable => @notable))
    flash[:notice] = "#{@note.title} has been created." if  @note.save
  end

  def edit
    @note = @current_shelter.notes.find(params[:id])
  end

  def update
    @note = @current_shelter.notes.find(params[:id])
    flash[:notice] = "#{@note.title} has been updated." if @note.update_attributes(params[:note])
  end

  def destroy
    @note = @current_shelter.notes.find(params[:id])
    @note.destroy
  end
end

app/views/notes/_edit_note.html.erb
<div class="box green" id="edit_note_<%=@note.id %>">
	<h2>Update note</h2>
	<div id="edit_note_errors_<%=@note.id %>"></div>
	<%= form_for (@note), :remote => true, :format => :js, :html => { :id => "edit_note_form_#{@note.id}", :class => "edit_note_form"} do |f| %>
    <ul>
      <%= render "form", :f => f %>
      <li class="buttons">
				<%= f.submit "Update Note", 'data-disable-with' => "Submitting...", :class => "button" %>
				&nbsp;&nbsp;or&nbsp;&nbsp;
				<%= link_to 'Cancel', '#',:onclick => "Notes.cancelForm(#{@note.id});"  %>
			</li>
		</ul>
	<% end %>
</div>

app/views/notes/_form.html.erb
<li>
	<%= f.label :title, "Title <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.text_field :title, :class => "field text large" %></div>
	<%= has_error_message?(@note, :title)%>
</li>

<% if defined?(default_category) && default_category %>
	<%= f.hidden_field :category, :value => Note::DEFAULT_CATEGORY %>
<% else %>
	<li id="note_category">
		<%= f.label :category, "Category <span class='req'>*</span>".html_safe, :class => "desc" %>
		<div>
		<%= f.collection_select :category, Note::CATEGORIES, :to_s, :humanize, :prompt => "Select Category", :class => "field select medium" %>
		</div>
		<%= has_error_message?(@note, :category)%>
	</li>
<% end %>

<% if @note.notable_type == "Animal" %>
  <li>
    <span>
      <%= f.check_box :hidden, :class =>"field checkbox" %>
		  <%= f.label :hidden, "Make this note private", :class => "desc choice" %>
    </span>
    <span>
      <i class="icon-question-sign tooltip" data-tip="Notes marked as Private can only be viewed by users for your account and will not be shared in the Community section. We advise this Private option only to be used for highly sensitive information."></i>
    </span>
    <%= has_error_message?(@note, :hidden)%>
  </li>
<% end %>

<li class="full">
	<%= f.label :description, :class => "desc" %>
	<div><%= f.text_area :description, :class => "field textarea medium" %></div>
	<%= has_error_message?(@note, :description)%>
</li>

app/views/notes/_note.html.erb
<%
    @documents = note.documents
    @uploader_documents = DocumentPresenter.as_uploader_collection(@documents)
%>
<script type="text/javascript">
  $(function() {
    Documents.initUploader(<%= note.id %>, <%= raw @uploader_documents %>, <%=Document::MAX_TOTAL%>);
  });
</script>

<div id="<%= dom_id(note) %>" class="note">
  <span class="created_date"><%= format_date_for(note.created_at, :short) %></span>

  <% if @documents.present? && (note.shelter_id == @current_shelter.id) %>
    <span class="attachment_icon"><%= image_tag "icon_paperclip.png" %></span>
  <% end %>

  <span class="details">
    <span class="title">
      <% if note.hidden? %><span class="icon-lock tooltip" data-tip="Private"></span><% end %>
      <%= note.title %>
    </span>
	</span>
	<span class="action_links">
    <% if note.shelter_id == @current_shelter.id  %>

      <% if can?(:attach_files, Note) %>
        <span class="add_documents_link">
          <%= link_to "Attach files", "#", :id => "add_documents_link", :class => "document_dialog",
            :"data-dialog-blur"    => "Notes.refreshNote(#{note.id})",
            :"data-dialog-element" => "#dialog_add_documents_#{note.id}",
            :"data-dialog-title"   => "Add or Remove attachments" %>
        </span>&nbsp;|&nbsp;
      <% end %>

      <% if can?(:update, Note) %>
        <span class="edit_link">
          <%= link_to "Edit", edit_note_path(note, :format => :js), :remote => true %>
        </span>
      <% end %>

      <% if can?(:destroy, Note) %>
        <span class="delete_link">&nbsp;|&nbsp;
          <%= link_to 'Delete', note,
            :confirm => "Are you sure you want to delete? This note will no longer be available and all attachments will be deleted.",
            :method => :delete, :remote => true, :format => :js %>
        </span>
      <% end %>

		<% end %>
  </span>

  <div class="description">
    <p><%= note.description.blank? ? "No description provided" : auto_link( simple_format(note.description), :all, :target => '_blank') %></p>
    <% if @documents.present? && (note.shelter_id == @current_shelter.id) %>
      <ul><strong>Attachments:</strong>
        <% @documents.each do |doc| %>
          <li><%= link_to doc.original_name, doc.document.url, :target => "_new" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= render "documents/dialog_add_documents", :attachable => note %>
</div>

app/views/notes/create.js.erb
<% if @note.errors.any? %>
	$('#create_note_errors').html( "<%= escape_javascript(render 'shared/error_messages', :target => @note) %>" );
	<%= render 'shared/ajax_form_errors', :target => @note, :form_id => "create_note_form" %>
<% else %>
	// Check Active Link and set to All if doesn't exist so it will work for other implementations of note (i.e. Parent)
	var note_filter_active = "All";
    if ($('.active_link').html()){
		note_filter_active = $('.active_link').html();
	}

	if (note_filter_active == '<%=@note.category%>' || note_filter_active == "All") {
		$('#notes').prepend("<%= escape_javascript(render @note) %>");
		$(".note").first().effect("highlight", {}, 1000);
	} else {
		$("#another_note_category").html('<div class="added_to_category"><p>Added to Category: <%= @note.category.humanize%> <!--<a href="#" onclick="$(this).parent().hide();">X</a>--></p></div>');
		$("#another_note_category").slideToggle(1500,function() {
			$(this).fadeOut(2000);
		});
	}

	// Clear Form
	$('#create_note_form').get(0).reset();

	// Remove Errors
	$('#create_note_errors').html("");
	$('#create_note_form p.error').remove();
  $('#create_note_form li').removeClass("error");

  // Google Anayltics
  <% if Rails.env.production? %>
    _gaq.push(['_trackPageview', "/notes/{id}/new"]);
  <% end %>

<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/notes/destroy.js.erb
$('#note_<%= @note.id %>').fadeOut(1000, function() {
	$(this).remove();
});

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/notes/{id}/destroy"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/notes/edit.js.erb
$('#note_<%=@note.id%>').hide();
$('#note_<%=@note.id%>').after("<%= escape_javascript(render 'edit_note', :collection => @note) %>");
$('#edit_note_<%=@note.id%>').show();

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/notes/{id}/edit"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/notes/show.js.erb
$('#note_<%=@note.id%>').replaceWith("<%= escape_javascript(render @note) %>");
$('#note_<%=@note.id%>').show().effect("highlight", {}, 2000);
$("#note_<%=@note.id%> .description").show();

<% flash.discard %>

app/views/notes/update.js.erb
<% if @note.errors.any? %>
	$('#edit_note_errors_<%=@note.id%>').html( "<%= escape_javascript(render 'shared/error_messages', :target => @note) %>" );
	<%= render 'shared/ajax_form_errors', :target => @note, :form_id => "edit_note_form_#{@note.id}" %>
<% else %>
	$('#edit_note_<%=@note.id%>').slideToggle(1000, function() { 
		$(this).remove(); 
	});
	$('#note_<%=@note.id%>').replaceWith( "<%= escape_javascript(render @note) %>" );
	$('#note_<%=@note.id%>').show().effect("highlight", {}, 2000);
	
	// Remove Errors
	$('#edit_note_errors_<%=@note.id %>').html("");
	$('#edit_note_form_<%=@note.id %> p.error').remove();
	$('#edit_note_form_<%=@note.id %> li').removeClass("error");
<% end %>
<% flash.discard %>