config/routes.rb
ShelterExchangeApp::Application.routes.draw do

  # Shared Functions
  #----------------------------------------------------------------------------
  namespace :shared do

    # Shared :: Breeds
    #----------------------------------------------------------------------------
    resources :breeds, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end

    # Shared :: Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end
  end
  #----------------------------------------------------------------------------


  # Application - Routes for *subdomain*.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::App) do

    # Notes
    #----------------------------------------------------------------------------
    resources :notes, :only => [:show, :create, :edit, :update, :destroy] do
      resources :documents, :only => [:create, :destroy]
    end

    # Status Histories
    #----------------------------------------------------------------------------
    resources :status_histories, :only => [:edit, :update, :destroy] do
    end

    # Items
    #----------------------------------------------------------------------------
    resources :items

    # Reports
    #----------------------------------------------------------------------------
    resources :reports do
      collection do
        get :custom
        get :status_by_month_year
        get :type_by_month_year
      end
    end

    # Locations
    #----------------------------------------------------------------------------
    resources :locations, :only => [:create, :edit, :update, :destroy] do
      collection do
        get :find_all
      end
    end

    # Accommodations
    #----------------------------------------------------------------------------
    resources :accommodations, :except => [:show]

    # Tasks
    #----------------------------------------------------------------------------
    resources :tasks, :except => [:show] do
      post :complete, :on => :member
    end

    # Communities
    #----------------------------------------------------------------------------
    resources :communities do
      collection do
        get :filter_notes
        get :find_animals_in_bounds
        get :find_animals_for_shelter
      end
    end

    # Maps
    #----------------------------------------------------------------------------
    resources :maps, :only => [:overlay]

    # Contacts
    #----------------------------------------------------------------------------
    resources :contacts do
      resources :notes
      collection do
        get :filter_animals_by_status
        get :find_by_full_name
        post :export
        post :import
        post :import_mapping
      end
    end

    # Photos
    #----------------------------------------------------------------------------
    resources :photos, :only => [:destroy]

    # Documents
    #----------------------------------------------------------------------------
    resources :documents, :only => [:destroy]

    # Animals
    #----------------------------------------------------------------------------
    resources :animals do
      resources :notes
      resources :tasks
      resources :photos, :only => [:create, :destroy] do
        get :refresh_gallery, :on => :collection
      end

      member do
        match :print, :via => [:get, :post]
      end

      collection do
        get :filter_notes
        get :auto_complete
        post :export
      end
    end

    # Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:index, :edit, :update]

    # Wish Lists
    #----------------------------------------------------------------------------
    resources :wish_lists, :only => [:edit, :update]

    # Capacities
    #----------------------------------------------------------------------------
    resources :capacities

    # Account Settings
    #----------------------------------------------------------------------------
    resources :settings, :only => [:index]
    match '/settings/:tab' => 'settings#index', :as => :setting

    resources :token_authentications, :only => [:create, :destroy]

    # Data Export
    #----------------------------------------------------------------------------
    match '/data_exports/download' => 'data_exports#download', :as => :download_data_exports
    resources :data_exports, :only => [:create]

    # Integrations
    #----------------------------------------------------------------------------
    resources :integrations, :only => [:create, :destroy]


    # Announcements
    #----------------------------------------------------------------------------
    resources :announcements do
      post :hide, :on => :collection
    end

    # Users
    #----------------------------------------------------------------------------
    resources :users, :except => [:show, :new, :create] do
      member do
        put :change_password
        post :change_owner
        get :valid_token
      end
      post :invite, :on => :collection
    end


    devise_for :users,
               :path => "",
               :path_names => { :sign_in => "login", :sign_out => "logout",
                                :confirmation => "confirmation", :invitation => "invitation" }


    # Dashboard
    #----------------------------------------------------------------------------
    match "/dashboard", :to => 'dashboard#index'

    # ROOT
    #----------------------------------------------------------------------------
    root :to => redirect("/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------




  # Admin - Routes for manage.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Admin) do

    namespace :admin do

      # Admin :: Dashboard
      #----------------------------------------------------------------------------
      resources :dashboard, :only => [:index]

      # Admin :: Shelters
      #----------------------------------------------------------------------------
      resources :shelters, :only => [:index, :show, :edit, :update] do
        get :live_search, :on => :collection
      end

      # Admin :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Integrations
      #----------------------------------------------------------------------------
      resources :integrations, :only => [:index]

      # Admin :: Users
      #----------------------------------------------------------------------------
      resources :users, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Announcements
      #----------------------------------------------------------------------------
      resources :announcements, :except => [:new]

      # Admin :: Accounts
      #----------------------------------------------------------------------------
      resources :accounts, :only => [:edit, :update]

      # Admin :: Export
      #----------------------------------------------------------------------------
      resources :exports, :only => [:index]
      match "exports/:export_type" => "exports#show", :as => :export, :defaults => { :format => :csv }, :via => [:get]

      # Admin :: Reports
      #----------------------------------------------------------------------------
      resources :reports do
        collection do
          get :custom
          get :status_by_month_year
          get :type_by_month_year
        end
      end
    end

    # Admin :: Owners :: Devise
    #----------------------------------------------------------------------------
    match '/login' => redirect('/admin/login')
    devise_for :owners, :path => "admin", :controllers => { :sessions => "admin/owners/sessions" },
                        :path_names => { :sign_in => "login", :sign_out => "logout" }



    # Root
    #----------------------------------------------------------------------------
    root :to => redirect("/admin/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Api - Routes for api.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Api) do

    namespace :api, :path => "/", :defaults => { :version => "v1" } do

      # Api :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        collection do
          get :search
        end
      end

      match '/:version/animals' => 'animals#index', via: [:get, :options], :as => :list_animals
      match '/:version/animals/search' => 'animals#search', via: [:get, :options], :as => :search_animals
    end

  end


#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Public - Routes for www.shelterexchange.org or shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Public) do

    namespace :public, :path => "/" do

      # Public :: Save A Life
      #----------------------------------------------------------------------------
      resources :save_a_life do
        collection do
          get :find_animals_in_bounds
        end

app/models/accommodation.rb
class Accommodation < ActiveRecord::Base
  default_scope :order => 'accommodations.name ASC'

  # Pagination
  #----------------------------------------------------------------------------
  self.per_page = 50

  # Associations
  #----------------------------------------------------------------------------
  belongs_to :shelter, :readonly => true
  belongs_to :animal_type, :readonly => true
  belongs_to :location, :readonly => true

  has_many :animals, :readonly => true

  # Validations
  #----------------------------------------------------------------------------
  validates :animal_type_id, :presence => {:message => "needs to be selected"}
  validates :name, :presence => true
  validates :max_capacity, :numericality => true

  # Searching
  #----------------------------------------------------------------------------
  def self.search_and_filter(query, type_id, location_id, order_by)
    scope = self.scoped
    scope = scope.includes(:animal_type, :location, :animals => [:photos, :animal_status])

    # Filter by type
    scope = scope.where(:animal_type_id => type_id) unless type_id.blank?

    # Filter by location
    scope = scope.where(:location_id => location_id) unless location_id.blank?

    # Search by query
    unless query.blank?
      query = query.strip.split.join("%")
      scope = scope.where("accommodations.name LIKE ?", "%#{query}%")
    end

    # Order by
    scope = scope.reorder(order_by) unless order_by.blank?
    scope
  end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  respond_to :html, :js

  def index
    query = params[:query]
    type_id = params[:animal_type_id]
    location_id = params[:location_id]
    order_by = params[:order_by]

    @accommodations = @current_shelter.accommodations.search_and_filter(query, type_id, location_id, order_by)
    @accommodations = @accommodations.paginate(:page => params[:page]).all

    redirect_to new_accommodation_path and return if request.format.html? && @accommodations.blank?
    respond_with(@accommodations)
  end

  def edit
    @accommodation = @current_shelter.accommodations.find(params[:id])
    respond_with(@accommodation)
  end

  def new
    @accommodation = @current_shelter.accommodations.new
    respond_with(@accommodation)
  end

  def create
    @accommodation = @current_shelter.accommodations.new(params[:accommodation])

    respond_with(@accommodation) do |format|
      if @accommodation.save
        flash[:notice] = "#{@accommodation.name} accommodation has been created."
        format.html { redirect_to accommodations_path }
      else
        format.html { render :action => :new }
      end
    end
  end

  def update
    @accommodation = @current_shelter.accommodations.find(params[:id])

    if @accommodation.update_attributes(params[:accommodation])
      flash[:notice] = "#{@accommodation.name} accommodation has been updated."
    end

    respond_with(@accommodation)
  end

  def destroy
    @accommodation = @current_shelter.accommodations.find(params[:id])
    flash[:notice] = "#{@accommodation.name} accommodation has been deleted." if @accommodation.destroy
    respond_with(@accommodation)
  end
end

app/views/accommodations/_accommodation.html.erb
<%
	animal_count = 	accommodation.animals.blank? ? 0 : accommodation.animals.count
  accommodation_class = (animal_count >= accommodation.max_capacity) ? "box red" : "box"
%>
<div id="accommodation_<%= accommodation.id %>" class="<%=accommodation_class%> accommodation">

	<div class="accommodation_info">
		<div class="accommodation_name">
			<h3><%= accommodation.name %></h3>
			<span class="location_details"><%= accommodation.location ? accommodation.location.name : "None" %></span>
		</div>

		<div class="accommodation_types">
			<span class="animal_type"><%= accommodation.animal_type.name %></span>
			<span class="select_link">
				<% if animal_count != accommodation.max_capacity %>
					<%= link_to "Select", "#", :onclick => "Animals.selectAccommodation('#{accommodation.id}','#{accommodation.name}');return false;" %>
				<% else %>
					Full
				<% end %>
			</span>
		</div>
	</div>

	<div class="accommodation_count">
		<span class="space_available">Space available: <%= accommodation.max_capacity - animal_count %></span>
		<div class="action_links">
			<span class="view_link">
				<%= link_to "View", "#", :onclick => "$('#accommodation_details_#{accommodation.id}').slideToggle();return false;" %>
			</span>

			<% if can?(:update, Accommodation) %>
        <span class="edit_link">&nbsp;|&nbsp;
          <%= link_to "Edit", edit_accommodation_path(accommodation, :format => :js), :remote => true %>
        </span>
      <% end %>

			<% if can?(:destroy, Accommodation) %>
        <span class="delete_link">&nbsp;|&nbsp;
          <%= link_to "Delete", accommodation, :method => :delete, :confirm => "Are you sure you want to delete? This will no longer display as an accommodation.", :remote => true, :format => :js %>
        </span>
      <% end %>

		</div>
	</div>

	<div id="accommodation_details_<%= accommodation.id %>" class="accommodation_details">
		<% if animal_count > 0 %>
		<table class="animal_list">
			<% accommodation.animals.each do |animal| %>
			<tr>
				<td class="image">
					<%= link_to image_tag(polymorphic_photo_url(animal.photos.first, :thumb)), animal_path(animal)  %>
				</td>
				<td class="details">
					<p><%= link_to animal.name, animal %></p>
					<p><% if animal.sex %><%= animal.sex.humanize %><% end %> <% if animal.is_sterilized %>(Sterilized)<% end %></p>
					<p><b><%= animal.animal_status.name %></b></p>
				</td>
			</tr>
			<% end %>
		</table>
		<% else %>
			<h3>No animals in this accommodation</h3>
		<% end %>
	</div>

</div>

app/views/accommodations/_accommodation_list.html.erb
<div class="accommodation_list">
	<%= render accommodations %>
</div>

<%= will_paginate accommodations %> 

app/views/accommodations/_dialog_accommodation_search.html.erb
<div id="dialog_accommodation_search" class="dialog">
	<div class="wrapper">
		<h3>Filter by specific location:</h3>
		<%= form_for :accommodations, :url => { :action => :search, :controller => :accommodations }, :remote => true, :format => :js, :html => { :id => "form_find_by_location", :method => :get } do |f| %>

      <%= collection_select(:filters, :location_id, @current_shelter.locations.all, :id, :name, {:prompt => "All"},
          { :name => "location_id", :onchange => "Accommodations.search();" } ) %><br /><br />
		<% end %>

		<div id="accommodations"></div>
	</div>
</div>

app/views/accommodations/_edit_accommodation.html.erb
<div class="box blue" id="edit_accommodation_<%=@accommodation.id %>">
	<h2>Update accommodation</h2>
	<div id="edit_accommodation_errors_<%=@accommodation.id %>"></div>
	<%= form_for (@accommodation), :remote => true, :format => :js, :html => { :id => "edit_accommodation_form_#{@accommodation.id}", :class => "edit_accommodation_form"} do |f| %>
		<ul>
			<%= render :partial => "form", :locals => { :f => f } %>
	    	<li class="buttons">
				<%= f.submit "Update Accommodation", 'data-disable-with' => "Submitting...", :class => "button" %>
				&nbsp;&nbsp;or&nbsp;&nbsp;
				<%= link_to 'Cancel', '#', :onclick => "Accommodations.cancelForm(#{@accommodation.id});return false;"  %>
			</li>
		</ul>
	<% end %>
</div>

app/views/accommodations/_form.html.erb
<li id="location_container">
	<%= f.label :location_id, "Location", :class => "desc" %>
	<div>
	<%= f.collection_select :location_id, @current_shelter.locations.all, :id, :name, {:include_blank =>  "None"}, {:class => "field select medium" } %>
	<% if can?(:update, Location) %>
	<a href="#" class="tooltip_dialog" data-dialog-element="#dialog_locations"
	                                   data-dialog-blur="Locations.findAllLocations()"
									   data-dialog-title="&nbsp;">Edit</a>
	<% end %>
	</div>
</li>
<li id="animal_type_container">
	<%= f.label :animal_type_id, "Animal type <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.collection_select :animal_type_id, AnimalType.all, :id, :name, {:include_blank =>  "Select one"}, {:class => "field select medium" } %></div>
	<%= has_error_message?(@accommodation, :animal_type_id)%>
</li>
<li id="name_container">
	<%= f.label :name, "Name <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.text_field :name, :class => "field text medium", :maxlength => 255, :placeholder => "Crate 1 or Kennel 3" %></div>
	<%= has_error_message?(@accommodation, :name)%>
</li>
<li id="max_capacity_container">
	<%= f.label :max_capacity, "Max number of animals <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.text_field :max_capacity, :class => "field text small", :maxlength => 4, :placeholder => "4" %></div>
	<%= has_error_message?(@accommodation, :max_capacity)%>
</li>

app/views/accommodations/create.js.erb
<% if @accommodation.errors.any? %>
	$('#create_accommodation_errors').html( "<%= escape_javascript(render 'shared/error_messages', :target => @accommodation) %>" );
	<%= render 'shared/ajax_form_errors', :target => @accommodation, :form_id => "create_accommodation_form" %>
<% else %>
	// Add Location
	$(".accommodation_list").prepend("<%= escape_javascript(render @accommodation) %>");
	$(".accommodation").first().effect("highlight", {}, 1000);

	// Clear Form
	$('#create_accommodation_form').get(0).reset();

	// Remove Errors
	$('#create_accommodation_errors').html("");
	$('#create_accommodation_form p.error').remove();
  $('#create_accommodation_form li').removeClass("error");

  // Google Anayltics
  <% if Rails.env.production? %>
    _gaq.push(['_trackPageview', "/accommodations/{id}/new"]);
  <% end %>

<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/accommodations/destroy.js.erb
$('#accommodation_<%= @accommodation.id %>').fadeOut(1000, function() {
	$(this).remove();
});

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/accommodations/{id}/destroy"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/accommodations/edit.js.erb
$('#accommodation_<%=@accommodation.id%>').hide();
$('#accommodation_<%=@accommodation.id%>').after("<%= escape_javascript(render 'edit_accommodation', :collection => @accommodation) %>");
$('#edit_accommodation_<%=@accommodation.id%>').show();

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/accommodations/{id}/edit"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/accommodations/full_search.js.erb
<% unless @accommodations.blank? %>
$('#accommodations').html( "<%= escape_javascript( render :partial => 'accommodation_list' ) %>" );
<% else %>
$('#accommodations').html( "<div class='no_results'><h2>No Accommodations found</h2></div>" );
<% end %>

app/views/accommodations/index.html.erb
<%= title "Accommodations" %>

<%= content_for :javascripts do %>
	<script type="text/javascript">
		$(function() {
			Locations.initializeDialog();
		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="print_heading">
		<h1>Accommodations</h1>
	</div>

	<div class="page_content">

    <div class="search">
      <h3>Search: <%= image_tag "icon_help.png", :class =>"tooltip", "data-tip" => "Search for the accommodation's name." %></h3>
      <%= form_for :accommodations, :html => { :id => "form_search", :onsubmit => "Accommodations.search(); return false;" } do |f| %>
      <ul>
        <li class="full">
          <%= text_field_tag "query", "", :placeholder => "Enter search term", :class => "field text"  %>
          <%= f.submit "Go" %>
        </li>
      </ul>
      <% end %>
    </div>

    <div class="filter_by">
      <h3>Filter by:</h3>
      <div class="filters">
        <span class="text">Type:</span>
        <span class="choice">
          <%= collection_select(:filters, :animal_type_id, AnimalType.all, :id, :name, {:prompt => "All"},
              { :name => "animal_type_id", :onchange => "Accommodations.search();" } ) %>
        </span>
        <span class="text">Location:</span>
          <span class="choice">
            <%= collection_select(:filters, :location_id, @current_shelter.locations.all, :id, :name, {:prompt => "All"},
                { :name => "location_id", :onchange => "Accommodations.search();" } ) %>
          </span>
          <span class="text">Order by:</span>
          <span class="choice">
            <select id="filters_order_by" name="order_by" onchange="Accommodations.search();">
              <option value="accommodations.name ASC">A-Z</option>
              <option value="accommodations.name DESC">Z-A</option>
              <option value="accommodations.updated_at DESC">Newest-Oldest</option>
              <option value="accommodations.updated_at ASC">Oldest-Newest</option>
            </select>
          </span>
      </div>
    </div>

		<div id="accommodations">
			<%= render 'accommodation_list', :accommodations => @accommodations %>
		</div>

	</div>

<% end %>

<%= content_for :sidebar do %>

  <% if can?(:create, Accommodation) %>
    <div id="create_accommodation" class="box orange">
      <h2>Create a new accommodation</h2>
      <div id="create_accommodation_errors"></div>
      <%= form_for (@accommodation = Accommodation.new), :remote => true, :format => :js, :html => { :id => "create_accommodation_form", :class => "create_accommodation_form" } do |f| %>
        <ul>
          <%= render :partial => "form", :locals => { :f => f } %>
          <li class="buttons">
            <%= f.submit "Create Accommodation", :disable_with => "Submitting...", :id => "create_accommodation_button", :class => "button"  %>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>

	<%= render "locations/dialog_locations" %>

<% end %>

app/views/accommodations/index.js.erb
<% unless @accommodations.blank? %>
  $('#accommodations').html( "<%= escape_javascript( render 'accommodation_list', :accommodations => @accommodations ) %>" );
<% else %>
  $('#accommodations').html( "<div class='no_results'><h2>No Accommodations found</h2></div>" );
<% end %>

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/accommodations/search_and_filter"]);
<% end %>

app/views/accommodations/new.html.erb
<%= title "Create your first accommodation" %>

<%= content_for :javascripts do %>
	<script type="text/javascript">
		$(function() {
			Locations.initializeDialog();
		});
	</script>

<% end %>

<%= content_for :page_content do %>

	<div class="page_heading">
		<h1>Create your first accommodation</h1>
		<p>Create a list of accommodations below to reflect your shelter floor plan or layout to better track where your animals are.</p>
		<ul class="help">
			<li><strong>Location</strong> - This field can be used as a high level description, for example Room 3, Building 2, or Barn 1. This is customizable for how you would like the locations named.</li>
			<li><strong>Animal type</strong> - Pick the animal type from the drop down menu for the accommodation you are creating. </li>
			<li><strong>Name</strong> - You can describe the accommodation in more detail - for example, Crate 1, or Kennel 4, or Stall 3. This is also customizable for your shelter.</li>
		</ul>
	</div>

	<div class="page_content">

    <% if can?(:create, Accommodation) %>
      <%= render "shared/error_messages", :target => @accommodation %>
      <div id="create_accommodation">
        <%= form_for @accommodation, :html => { :id => "create_accommodation_form", :class => "create_accommodation_form" } do |f| %>
          <ul>
            <%= render "form", :f => f %>
              <li class="buttons">
              <%= f.submit "Create Accommodation", 'data-disable-with' => "Submitting...", :class => "button" %>
            </li>
          </ul>
        <% end %>
      </div>
    <% end %>

	</div>

	<%= render "locations/dialog_locations" %>

<% end %>

<%= content_for :sidebar do %>
<% end %>

app/views/accommodations/update.js.erb
<% if @accommodation.errors.any? %>
	$('#edit_accommodation_errors_<%=@accommodation.id %>').html( "<%= escape_javascript(render 'shared/error_messages', :target => @accommodation) %>" );
	<%= render 'shared/ajax_form_errors', :target => @accommodation, :form_id => "edit_accommodation_form_#{@accommodation.id}" %>
<% else %>
	//Update Location
	$('#edit_accommodation_<%=@accommodation.id%>').slideToggle(800, function() {
		$(this).remove();
	});
	$('#accommodation_<%=@accommodation.id%>').replaceWith( "<%= escape_javascript(render @accommodation) %>" );
	$('#accommodation_<%=@accommodation.id%>').fadeIn(1000).effect("highlight", {}, 1000);

	// Remove Errors
	$('#edit_accommodation_errors_<%=@accommodation.id %>').html("");
	$('#edit_accommodation_form_<%=@accommodation.id %> p.error').remove();
  $('#edit_accommodation_form_<%=@accommodation.id %> li').removeClass("error");

<% end %>
<% flash.discard %>