config/routes.rb
ShelterExchangeApp::Application.routes.draw do

  # Shared Functions
  #----------------------------------------------------------------------------
  namespace :shared do

    # Shared :: Breeds
    #----------------------------------------------------------------------------
    resources :breeds, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end

    # Shared :: Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end
  end
  #----------------------------------------------------------------------------


  # Application - Routes for *subdomain*.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::App) do

    # Notes
    #----------------------------------------------------------------------------
    resources :notes, :only => [:show, :create, :edit, :update, :destroy] do
      resources :documents, :only => [:create, :destroy]
    end

    # Status Histories
    #----------------------------------------------------------------------------
    resources :status_histories, :only => [:edit, :update, :destroy] do
    end

    # Items
    #----------------------------------------------------------------------------
    resources :items

    # Reports
    #----------------------------------------------------------------------------
    resources :reports do
      collection do
        get :custom
        get :status_by_month_year
        get :type_by_month_year
      end
    end

    # Locations
    #----------------------------------------------------------------------------
    resources :locations, :only => [:create, :edit, :update, :destroy] do
      collection do
        get :find_all
      end
    end

    # Accommodations
    #----------------------------------------------------------------------------
    resources :accommodations, :except => [:show]

    # Tasks
    #----------------------------------------------------------------------------
    resources :tasks, :except => [:show] do
      post :complete, :on => :member
    end

    # Communities
    #----------------------------------------------------------------------------
    resources :communities do
      collection do
        get :filter_notes
        get :find_animals_in_bounds
        get :find_animals_for_shelter
      end
    end

    # Maps
    #----------------------------------------------------------------------------
    resources :maps, :only => [:overlay]

    # Contacts
    #----------------------------------------------------------------------------
    resources :contacts do
      resources :notes
      collection do
        get :filter_animals_by_status
        get :find_by_full_name
        post :export
        post :import
        post :import_mapping
      end
    end

    # Photos
    #----------------------------------------------------------------------------
    resources :photos, :only => [:destroy]

    # Documents
    #----------------------------------------------------------------------------
    resources :documents, :only => [:destroy]

    # Animals
    #----------------------------------------------------------------------------
    resources :animals do
      resources :notes
      resources :tasks
      resources :photos, :only => [:create, :destroy] do
        get :refresh_gallery, :on => :collection
      end

      member do
        match :print, :via => [:get, :post]
      end

      collection do
        get :filter_notes
        get :auto_complete
        post :export
      end
    end

    # Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:index, :edit, :update]

    # Wish Lists
    #----------------------------------------------------------------------------
    resources :wish_lists, :only => [:edit, :update]

    # Capacities
    #----------------------------------------------------------------------------
    resources :capacities

    # Account Settings
    #----------------------------------------------------------------------------
    resources :settings, :only => [:index]
    match '/settings/:tab' => 'settings#index', :as => :setting

    resources :token_authentications, :only => [:create, :destroy]

    # Data Export
    #----------------------------------------------------------------------------
    match '/data_exports/download' => 'data_exports#download', :as => :download_data_exports
    resources :data_exports, :only => [:create]

    # Integrations
    #----------------------------------------------------------------------------
    resources :integrations, :only => [:create, :destroy]


    # Announcements
    #----------------------------------------------------------------------------
    resources :announcements do
      post :hide, :on => :collection
    end

    # Users
    #----------------------------------------------------------------------------
    resources :users, :except => [:show, :new, :create] do
      member do
        put :change_password
        post :change_owner
        get :valid_token
      end
      post :invite, :on => :collection
    end


    devise_for :users,
               :path => "",
               :path_names => { :sign_in => "login", :sign_out => "logout",
                                :confirmation => "confirmation", :invitation => "invitation" }


    # Dashboard
    #----------------------------------------------------------------------------
    match "/dashboard", :to => 'dashboard#index'

    # ROOT
    #----------------------------------------------------------------------------
    root :to => redirect("/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------




  # Admin - Routes for manage.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Admin) do

    namespace :admin do

      # Admin :: Dashboard
      #----------------------------------------------------------------------------
      resources :dashboard, :only => [:index]

      # Admin :: Shelters
      #----------------------------------------------------------------------------
      resources :shelters, :only => [:index, :show, :edit, :update] do
        get :live_search, :on => :collection
      end

      # Admin :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Integrations
      #----------------------------------------------------------------------------
      resources :integrations, :only => [:index]

      # Admin :: Users
      #----------------------------------------------------------------------------
      resources :users, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Announcements
      #----------------------------------------------------------------------------
      resources :announcements, :except => [:new]

      # Admin :: Accounts
      #----------------------------------------------------------------------------
      resources :accounts, :only => [:edit, :update]

      # Admin :: Export
      #----------------------------------------------------------------------------
      resources :exports, :only => [:index]
      match "exports/:export_type" => "exports#show", :as => :export, :defaults => { :format => :csv }, :via => [:get]

      # Admin :: Reports
      #----------------------------------------------------------------------------
      resources :reports do
        collection do
          get :custom
          get :status_by_month_year
          get :type_by_month_year
        end
      end
    end

    # Admin :: Owners :: Devise
    #----------------------------------------------------------------------------
    match '/login' => redirect('/admin/login')
    devise_for :owners, :path => "admin", :controllers => { :sessions => "admin/owners/sessions" },
                        :path_names => { :sign_in => "login", :sign_out => "logout" }



    # Root
    #----------------------------------------------------------------------------
    root :to => redirect("/admin/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Api - Routes for api.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Api) do

    namespace :api, :path => "/", :defaults => { :version => "v1" } do

      # Api :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        collection do
          get :search
        end
      end

      match '/:version/animals' => 'animals#index', via: [:get, :options], :as => :list_animals
      match '/:version/animals/search' => 'animals#search', via: [:get, :options], :as => :search_animals
    end

  end


#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Public - Routes for www.shelterexchange.org or shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Public) do

    namespace :public, :path => "/" do

      # Public :: Save A Life
      #----------------------------------------------------------------------------
      resources :save_a_life do
        collection do
          get :find_animals_in_bounds
        end

app/models/capacity.rb
class Capacity < ActiveRecord::Base

  # Associations
  #----------------------------------------------------------------------------
  belongs_to :shelter, :readonly => true
  belongs_to :animal_type, :readonly => true

  # Validations
  #----------------------------------------------------------------------------
  validates :animal_type_id, :presence   => { :message => "needs to be selected" },
                             :uniqueness => { :scope => :shelter_id, :message => "is already in use" }
  validates :max_capacity, :numericality => true

  # Instance Methods
  #----------------------------------------------------------------------------
  def animal_count(shelter)
    self.animal_type.animals.for_capacity.where(:shelter_id => shelter).limit(nil).count
  end
end

app/controllers/capacities_controller.rb
class CapacitiesController < ApplicationController
  respond_to :html, :js

  def index
    @capacities = @current_shelter.capacities.includes(:animal_type).all
    redirect_to new_capacity_path if @capacities.blank?
  end

  def new
    @capacity = @current_shelter.capacities.new
    respond_with(@capacity)
  end

  def create
    @capacity = @current_shelter.capacities.new(params[:capacity])
    respond_with(@capacity) do |format|
      if @capacity.save
        flash[:notice] = "Shelter Capacity has been created."
        format.html { redirect_to capacities_path }
      else
        format.html { render :action => :new }
      end
    end
  end

  def edit
    @capacity = @current_shelter.capacities.find(params[:id])
    respond_with(@capacity)
  end

  def update
    @capacity = @current_shelter.capacities.find(params[:id])
    flash[:notice] = "Shelter Capacity has been updated." if @capacity.update_attributes(params[:capacity])
    respond_with(@capacity)
  end

  def destroy
    @capacity = @current_shelter.capacities.find(params[:id])
    flash[:notice] = "Shelter Capacity has been deleted." if @capacity.destroy
    respond_with(@capacity)
  end
end

app/helpers/capacities_helper.rb
module CapacitiesHelper

  def capacity_status(capacity, animal_count)
    if (animal_count >= (capacity.max_capacity * 0.8).round.to_i)
      "red"
    elsif (animal_count >= (capacity.max_capacity * 0.6).round.to_i) &&
          (animal_count < (capacity.max_capacity * 0.8).round.to_i)
      "yellow"
    elsif (animal_count < (capacity.max_capacity * 0.6).round.to_i)
      "green"
    end
  end
end

app/views/capacities/_capacity.html.erb
<% animal_count = capacity.animal_count(@shelter || @current_shelter) %>
<% status_class = capacity_status(capacity, animal_count) %>

<div id="<%= dom_id(capacity) %>" class="capacity">

	<span class="status"><div class="circle medium <%=status_class%>"><%= capacity.animal_type.name %></div></span>
	<span class="counts">
		<ul>
			<li class="max"><strong>Max capacity:</strong> <%= capacity.max_capacity%></li>
			<li class="available"><strong>Available space:</strong> <%= capacity.max_capacity - animal_count %></li>
		</ul>
	</span>

  <span class="action_links">

    <% if can?(:update, Capacity) %>
      <span class="edit_link">
        <%= link_to "Edit", edit_capacity_path(capacity, :format => :js), :remote => true %>
      </span>
    <% end %>

		<% if can?(:destroy, Capacity) %>
			<span class="delete_link">&nbsp;|&nbsp;
				<%= link_to "Delete", capacity, :confirm => "Are you sure?", :method => :delete, :remote => true, :format => :js %>
			</span>
    <% end %>

  </span>

</div>

app/views/capacities/_capacity_list.html.erb
<div id="capacities" class="capacity_list">
	<%= render @capacities %>
</div>

<div class="legend">
	<table>
		<tr><th>Legend:</th></tr>
		<tr><td><div class="circle small red"><span>80% Full</span></div></td></tr>
		<tr><td><div class="circle small yellow"><span>60% Full</span></div></td></tr>
		<tr><td><div class="circle small green"><span>Good</span></div></td></tr>
	</table>
</div>

app/views/capacities/_edit_capacity.html.erb
<div class="box blue" id="edit_capacity_<%=@capacity.id %>">
	<h2>Update capacity</h2>
	<div id="edit_capacity_errors_<%= @capacity.id %>"></div>
	<%= form_for (@capacity), :remote => true, :format => :js, :html => { :id => "edit_capacity_form_#{@capacity.id}", :class => "edit_capacity_form" } do |f| %>
		<ul>
			<%= render "form", :f => f  %>
	    	<li class="buttons">
				<%= f.submit "Update Capacity", 'data-disable-with' => "Submitting...", :class => "button" %>
				&nbsp;&nbsp;or&nbsp;&nbsp;
				<%= link_to 'Cancel', '#', :onclick => "Capacities.cancelForm(#{@capacity.id});return false;"  %>
			</li>
		</ul>
	<% end %>
</div>

app/views/capacities/_form.html.erb
<li id="animal_type_container" class="full">
	<%= f.label :animal_type_id, "Animal type <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.collection_select :animal_type_id, AnimalType.all, :id, :name, {:include_blank =>  "Select one"}, :class => "field select medium" %></div>
	<%= has_error_message?(@capacity, :animal_type_id)%>
</li>
<li id="max_capacity_container" class="full">
	<%= f.label :max_capacity, "Max capacity of animals per type <span class='req'>*</span>".html_safe, :class => "desc" %>
	<div><%= f.text_field :max_capacity, :class => "field text small", :maxlength => 4, :placeholder => "100" %></div>
	<%= has_error_message?(@capacity, :max_capacity)%>
</li>

app/views/capacities/create.js.erb
<% if @capacity.errors.any? %>
	$('#create_capacity_errors').html( "<%= escape_javascript(render 'shared/error_messages', :target => @capacity) %>" );
	<%= render 'shared/ajax_form_errors', :target => @capacity, :form_id => "create_capacity_form" %>
<% else %>
  $('#capacity_help').hide();
	$('#capacities').prepend("<%= escape_javascript(render 'capacity', :capacity => @capacity) %>");
	$(".capacity").first().effect("highlight", {}, 1500);

	// Clear Form
	$('#create_capacity_form').get(0).reset();

	// Remove Errors
	$('#create_capacity_errors').html("");
	$('#create_capacity_form p.error').remove();
  $('#create_capacity_form li').removeClass("error");

  // Google Anayltics
  <% if Rails.env.production? %>
    _gaq.push(['_trackPageview', "/capacities/{id}/new"]);
  <% end %>

<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/capacities/destroy.js.erb
$('#capacity_<%= @capacity.id %>').fadeOut(1000, function() {
	$(this).remove();
});

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/capacities/{id}/destroy"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/capacities/edit.js.erb
$('#capacity_<%=@capacity.id%>').hide();
$('#capacity_<%=@capacity.id%>').after( "<%= escape_javascript(render 'edit_capacity', :collection => @capacity) %>" );
$('#edit_capacity_<%=@capacity.id%>').show();

// Google Anayltics
<% if Rails.env.production? %>
  _gaq.push(['_trackPageview', "/capacities/{id}/edit"]);
<% end %>

// Discard Flash Message
<% flash.discard %>

app/views/capacities/index.html.erb
<%= title "Capacities" %>

<%= content_for :javascripts do %>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading blue">
		<h1>Shelter capacity</h1>
	</div>

	<div class="page_content">
		<%= render "capacity_list" %>
	</div>

<% end %>

<%= content_for :sidebar do %>

  <% if can?(:create, Capacity) %>
    <div id="create_capacity" class="box orange">
      <h2>Add a capacity</h2>
      <div id="create_capacity_errors"></div>
      <%= form_for (@capacity = Capacity.new), :remote => true, :format => :js, :html => { :id => "create_capacity_form", :class => "create_capacity_form" } do |f| %>
        <ul>
          <%= render "form", :f => f  %>
          <li class="buttons">
            <%= f.submit "Create Capacity", 'data-disable-with' => "Submitting...", :class => "button"  %>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>


<% end %>

app/views/capacities/new.html.erb
<%= title "Create your first capacity" %>

<%= content_for :page_content do %>

	<div class="page_heading">
		<h1>Create your Shelter Capacity List</h1>
		<p>Enter the maximum number of animals per type that your facility can house, include a warning level number to reflect when you are close to capacity.</p>
		<p>This information will be shown on the Community and Public maps to encourage assistance to your facility by warning people when you are close or at capacity.</p>
	</div>

	<div class="page_content">

    <% if can?(:create, Capacity) %>
      <%= render "shared/error_messages", :target => @capacity %>
      <div id="create_capacity">
        <%= form_for @capacity, :html => { :id => "create_capacity_form", :class => "create_capacity_form" } do |f| %>
          <ul>
            <%= render "form", :f => f  %>
              <li class="buttons">
              <%= f.submit "Create Capacity", 'data-disable-with' => "Submitting...", :class => 'button' %>
            </li>
          </ul>
        <% end %>
      </div>
    <% end %>

<% end %>

app/views/capacities/update.js.erb
<% if @capacity.errors.any? %>
	$('#edit_capacity_errors_<%=@capacity.id%>').html( "<%= escape_javascript(render 'shared/error_messages', :target => @capacity) %>" );
	<%= render 'shared/ajax_form_errors', :target => @capacity, :form_id => "edit_capacity_form_#{@capacity.id}" %>
<% else %>
	$('#edit_capacity_<%=@capacity.id%>').slideToggle(1000, function() { 
		$(this).remove(); 
	});
	$('#capacity_<%=@capacity.id%>').replaceWith( "<%= escape_javascript(render @capacity) %>" );
	$('#capacity_<%=@capacity.id%>').fadeIn(1000).effect("highlight", {}, 2000);

	// Remove Errors
	$('#edit_capacity_errors_<%=@capacity.id %>').html("");
	$('#edit_capacity_form_<%=@capacity.id %> p.error').remove();
	$('#edit_capacity_form_<%=@capacity.id %> li').removeClass("error");
<% end %>
<% flash.discard %>