config/routes.rb
ShelterExchangeApp::Application.routes.draw do

  # Shared Functions
  #----------------------------------------------------------------------------
  namespace :shared do

    # Shared :: Breeds
    #----------------------------------------------------------------------------
    resources :breeds, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end

    # Shared :: Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:auto_complete] do
      get :auto_complete, :on => :collection
    end
  end
  #----------------------------------------------------------------------------


  # Application - Routes for *subdomain*.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::App) do

    # Notes
    #----------------------------------------------------------------------------
    resources :notes, :only => [:show, :create, :edit, :update, :destroy] do
      resources :documents, :only => [:create, :destroy]
    end

    # Status Histories
    #----------------------------------------------------------------------------
    resources :status_histories, :only => [:edit, :update, :destroy] do
    end

    # Items
    #----------------------------------------------------------------------------
    resources :items

    # Reports
    #----------------------------------------------------------------------------
    resources :reports do
      collection do
        get :custom
        get :status_by_month_year
        get :type_by_month_year
      end
    end

    # Locations
    #----------------------------------------------------------------------------
    resources :locations, :only => [:create, :edit, :update, :destroy] do
      collection do
        get :find_all
      end
    end

    # Accommodations
    #----------------------------------------------------------------------------
    resources :accommodations, :except => [:show]

    # Tasks
    #----------------------------------------------------------------------------
    resources :tasks, :except => [:show] do
      post :complete, :on => :member
    end

    # Communities
    #----------------------------------------------------------------------------
    resources :communities do
      collection do
        get :filter_notes
        get :find_animals_in_bounds
        get :find_animals_for_shelter
      end
    end

    # Maps
    #----------------------------------------------------------------------------
    resources :maps, :only => [:overlay]

    # Contacts
    #----------------------------------------------------------------------------
    resources :contacts do
      resources :notes
      collection do
        get :filter_animals_by_status
        get :find_by_full_name
        post :export
        post :import
        post :import_mapping
      end
    end

    # Photos
    #----------------------------------------------------------------------------
    resources :photos, :only => [:destroy]

    # Documents
    #----------------------------------------------------------------------------
    resources :documents, :only => [:destroy]

    # Animals
    #----------------------------------------------------------------------------
    resources :animals do
      resources :notes
      resources :tasks
      resources :photos, :only => [:create, :destroy] do
        get :refresh_gallery, :on => :collection
      end

      member do
        match :print, :via => [:get, :post]
      end

      collection do
        get :filter_notes
        get :auto_complete
        post :export
      end
    end

    # Shelters
    #----------------------------------------------------------------------------
    resources :shelters, :only => [:index, :edit, :update]

    # Wish Lists
    #----------------------------------------------------------------------------
    resources :wish_lists, :only => [:edit, :update]

    # Capacities
    #----------------------------------------------------------------------------
    resources :capacities

    # Account Settings
    #----------------------------------------------------------------------------
    resources :settings, :only => [:index]
    match '/settings/:tab' => 'settings#index', :as => :setting

    resources :token_authentications, :only => [:create, :destroy]

    # Data Export
    #----------------------------------------------------------------------------
    match '/data_exports/download' => 'data_exports#download', :as => :download_data_exports
    resources :data_exports, :only => [:create]

    # Integrations
    #----------------------------------------------------------------------------
    resources :integrations, :only => [:create, :destroy]


    # Announcements
    #----------------------------------------------------------------------------
    resources :announcements do
      post :hide, :on => :collection
    end

    # Users
    #----------------------------------------------------------------------------
    resources :users, :except => [:show, :new, :create] do
      member do
        put :change_password
        post :change_owner
        get :valid_token
      end
      post :invite, :on => :collection
    end


    devise_for :users,
               :path => "",
               :path_names => { :sign_in => "login", :sign_out => "logout",
                                :confirmation => "confirmation", :invitation => "invitation" }


    # Dashboard
    #----------------------------------------------------------------------------
    match "/dashboard", :to => 'dashboard#index'

    # ROOT
    #----------------------------------------------------------------------------
    root :to => redirect("/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------




  # Admin - Routes for manage.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Admin) do

    namespace :admin do

      # Admin :: Dashboard
      #----------------------------------------------------------------------------
      resources :dashboard, :only => [:index]

      # Admin :: Shelters
      #----------------------------------------------------------------------------
      resources :shelters, :only => [:index, :show, :edit, :update] do
        get :live_search, :on => :collection
      end

      # Admin :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Integrations
      #----------------------------------------------------------------------------
      resources :integrations, :only => [:index]

      # Admin :: Users
      #----------------------------------------------------------------------------
      resources :users, :only => [:index] do
        get :live_search, :on => :collection
      end

      # Admin :: Announcements
      #----------------------------------------------------------------------------
      resources :announcements, :except => [:new]

      # Admin :: Accounts
      #----------------------------------------------------------------------------
      resources :accounts, :only => [:edit, :update]

      # Admin :: Export
      #----------------------------------------------------------------------------
      resources :exports, :only => [:index]
      match "exports/:export_type" => "exports#show", :as => :export, :defaults => { :format => :csv }, :via => [:get]

      # Admin :: Reports
      #----------------------------------------------------------------------------
      resources :reports do
        collection do
          get :custom
          get :status_by_month_year
          get :type_by_month_year
        end
      end
    end

    # Admin :: Owners :: Devise
    #----------------------------------------------------------------------------
    match '/login' => redirect('/admin/login')
    devise_for :owners, :path => "admin", :controllers => { :sessions => "admin/owners/sessions" },
                        :path_names => { :sign_in => "login", :sign_out => "logout" }



    # Root
    #----------------------------------------------------------------------------
    root :to => redirect("/admin/dashboard"), :via => [:get]
  end



#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Api - Routes for api.shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Api) do

    namespace :api, :path => "/", :defaults => { :version => "v1" } do

      # Api :: Animals
      #----------------------------------------------------------------------------
      resources :animals, :only => [:index] do
        collection do
          get :search
        end
      end

      match '/:version/animals' => 'animals#index', via: [:get, :options], :as => :list_animals
      match '/:version/animals/search' => 'animals#search', via: [:get, :options], :as => :search_animals
    end

  end


#--------------------------------------------------------------------------------------------------------------------------------------------------------



  # Public - Routes for www.shelterexchange.org or shelterexchange.org
  #----------------------------------------------------------------------------
  constraints(Subdomains::Public) do

    namespace :public, :path => "/" do

      # Public :: Save A Life
      #----------------------------------------------------------------------------
      resources :save_a_life do
        collection do
          get :find_animals_in_bounds
        end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::ApplicationController
  respond_to :html, :js, :json

  def index
    @status_counts = StatusHistory.status_counts(3).all
  end

  def custom
    respond_to do |format|
      format.html
      format.json {
        selected_year = params[:selected_year] || Time.zone.today.year
        status = params[:status].to_sym rescue nil
        by_type = params[:by_type].to_boolean rescue false

        # TODO: add state to these queries later
        results = StatusHistory.totals_by_month(selected_year, status, by_type).all

        render :json => results.collect{ |result| { :type => result.type, :jan => result.january.to_i, :feb => result.february.to_i, :mar => result.march.to_i, :apr => result.april.to_i, :may => result.may.to_i, :jun => result.june.to_i, :jul => result.july.to_i, :aug => result.august.to_i, :sep => result.september.to_i, :oct => result.october.to_i, :nov => result.november.to_i, :dec => result.december.to_i } }.to_json
      }
    end
  end

  def status_by_month_year
    respond_to do |format|
      format.html
      format.json {
        results = StatusHistory.status_by_month_year(params[:selected_month], params[:selected_year], params[:selected_state]).all
        render :json => results.collect{ |result| { :name => result.name, :count => result.count.to_i } }.to_json
      }
    end
  end

  def type_by_month_year
    respond_to do |format|
      format.html
      format.json {
        results = Animal.type_by_month_year(params[:selected_month], params[:selected_year], nil, params[:selected_state]).all
        render :json => results.collect{ |result| { :name => result.name, :count => result.count.to_i } }.to_json
      }
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :html, :js, :json

  def index
    @current_counts = @current_shelter.animals.count_by_status.active
    @status_counts = @current_shelter.status_histories.status_counts(3).all
  end

  def custom
    respond_to do |format|
      format.html
      format.json {
        selected_year = params[:selected_year] || Time.zone.today.year
        status = params[:status].to_sym rescue nil
        by_type = params[:by_type].to_boolean rescue false
        results = @current_shelter.status_histories.totals_by_month(selected_year, status, by_type)

        render :json => results.collect{ |result| { :type => result.type, :jan => result.january.to_i, :feb => result.february.to_i, :mar => result.march.to_i, :apr => result.april.to_i, :may => result.may.to_i, :jun => result.june.to_i, :jul => result.july.to_i, :aug => result.august.to_i, :sep => result.september.to_i, :oct => result.october.to_i, :nov => result.november.to_i, :dec => result.december.to_i } }.to_json
      }
    end
  end

  def status_by_month_year
    respond_to do |format|
      format.html
      format.json {
        results = @current_shelter.status_histories.status_by_month_year(params[:selected_month], params[:selected_year]).all
        render :json => results.collect{ |result| { :name => result.name, :count => result.count.to_i } }.to_json
      }
    end
  end

  def type_by_month_year
    respond_to do |format|
      format.html
      format.json {
        results = @current_shelter.animals.type_by_month_year(params[:selected_month], params[:selected_year], @current_shelter.id)
        render :json => results.collect{ |result| { :name => result.name, :count => result.count.to_i } }.to_json
      }
    end
  end
end

app/views/reports/_sidebar.html.erb
<% years = (Time.zone.today.year-5..Time.zone.today.year).to_a.reverse %>
<% selected_year = params[:selected_year] || Time.zone.today.year %>

<div class="box blue">
  <h2>Yearly Totals (by Month)</h2>
  <%= form_tag custom_reports_path, :method => :get, :id => "form_custom_reports" do %>
    <ul>
      <li>
        <%= label_tag :status, "Animal Status", :class => "desc" %>
        <%= select_tag :status, options_for_select(
            AnimalStatus.all.map{|status| [status.name, status.name.parameterize.underscore] }, params[:status]
          ), :prompt => "Select one" %>
      </li>
      <li>
        <%= label_tag :selected_year, "Year", :class => "desc" %>
        <div>
          <%= select_tag :selected_year, options_for_select(years, selected_year), :prompt => "Select one" %>
        </div>
      </li>
      <li>
        <%= label_tag :by_type, "Display", :class => "desc" %>
        <div>
          <%= radio_button_tag :by_type, false, (params[:by_type] != "true"), :class => "field radio" %>
          <%= label_tag "false", "Combined totals", :class => "choice" %>
        </div>
        <div>
          <%= radio_button_tag :by_type, true, (params[:by_type] == "true"), :class => "field radio" %>
          <%= label_tag "true", "Totals by animal type", :class => "choice" %>
        </div>
      </li>
      <li class="buttons">
        <%= submit_tag "Run report", :name => nil, 'data-disable-with' => "Running...", :class => 'button' %>
      </li>
    </ul>
	<% end %>
</div>

app/views/reports/adoption_monthly_total.html.erb
<%= title "Adoption Monthly Total - Reports"  %>

<%= content_for :javascripts do %>
	<%= javascript_include_tag "highcharts", "reports/reports", :cache => "cache/application/reports-index" %>
	<script type="text/javascript">
		$(function() {
			Reports.barChart('Adoption Monthly Total', 'adoption_monthly_total', 'Adoptions');
		});
	</script>
<% end %>

<%= content_for :page_content do %>
	
	<div class="page_heading yellow_background">
		<h1>Reports</h1>
		<div class="action_links">
			<%= label_tag :report_selected_year, "Select year" %>
			<%= select_year(Date.today, {:field_name => :report_selected_year, :start_year => current_year - 3, :end_year => current_year}, {:onchange => "Reports.barChart('Adoption Monthly Total', 'adoption_monthly_total', 'Adoptions');"})%>
		</div>
	</div>
	
	<div class="page_content">
		<div id="adoption_monthly_total" class="report"></div>
	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>

app/views/reports/adoption_monthly_total_by_type.html.erb
<%= title "Adoption Monthly Total by Animal Type - Reports"  %>

<%= content_for :javascripts do %>
	<%= javascript_include_tag "highcharts", "reports/reports", :cache => "cache/application/reports-index" %>
	<script type="text/javascript">
		$(function() {
			Reports.barChart('Adoption Monthly Total By Type', 'adoption_monthly_total_by_type', 'Adoptions');
		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading yellow_background">
		<h1>Reports</h1>
		<div class="action_links">
			<%= label_tag :report_selected_year, "Select year" %>
			<%= select_year(Date.today, {:field_name => :report_selected_year, :start_year => current_year - 3, :end_year => current_year}, {:onchange => "Reports.barChart('Adoption Monthly Total By Type', 'adoption_monthly_total_by_type', 'Adoptions');"})%>
		</div>
	</div>
	<div class="page_content">
		<div id="adoption_monthly_total_by_type" class="report"></div>
	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>

app/views/reports/custom.html.erb
<% by_type = params[:by_type] || false %>
<% report_title = "#{params[:status].titleize} Monthly Total"  %>

<% if by_type %>
  <% report_title += " by Animal Type"  %>
<% end %>

<%= title report_title  %>

<%= content_for :javascripts do %>
  <script type="text/javascript">
    $(function() {
      Reports.barChart('<%= report_title %>', '<%= params[:status] %>', <%= by_type %>, '<%= params[:status].titleize %>');

      $("#form_csv_export_reports").submit(function(e) {
        $("#csv_string", this).val(barChart.getCSV());
      });

		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading blue">
		<h1>Reports</h1>
	</div>

	<div class="page_content">

		<div id="custom_report" class="report"></div>

    <%= form_tag csv_export_reports_path(:format => :csv), :method => :post, :id => "form_csv_export_reports" do %>
      <ul>
        <li class="buttons">
          <%= hidden_field_tag :csv_string %>
          <%= submit_tag "Export as CSV", :name => nil, :class => "button" %>
        </li>
      </ul>
	  <% end %>

	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>

app/views/reports/euthanasia_monthly_total.html.erb
<%= title "Euthanasia Monthly Total - Reports"  %>

<%= content_for :javascripts do %>
	<%= javascript_include_tag "highcharts", "reports/reports", :cache => "cache/application/reports-index" %>
	<script type="text/javascript">
		$(function() {
			Reports.barChart('Euthanasia Monthly Total', 'euthanasia_monthly_total', 'Euthanized');
		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading yellow_background">
		<h1>Reports</h1>
		<div class="action_links">
			<%= label_tag :report_selected_year, "Select year" %>
			<%= select_year(Date.today, {:field_name => :report_selected_year, :start_year => current_year - 3, :end_year => current_year}, {:onchange => "Reports.barChart('Euthanasia Monthly Total', 'euthanasia_monthly_total', 'Euthanized');"})%>
		</div>
	</div>
	<div class="page_content">
		<div id="euthanasia_monthly_total" class="report"></div>
	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>

app/views/reports/euthanasia_monthly_total_by_type.html.erb
<%= title "Euthanasia Monthly Total by Animal Type - Reports"  %>

<%= content_for :javascripts do %>
	<%= javascript_include_tag "highcharts", "reports/reports", :cache => "cache/application/reports-index" %>
	<script type="text/javascript">
		$(function() {
			Reports.barChart('Euthanasia Monthly Total By Type', 'euthanasia_monthly_total_by_type', 'Euthanized');
		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading yellow_background">
		<h1>Reports</h1>
		<div class="action_links">
			<%= label_tag :report_selected_year, "Select year" %>
			<%= select_year(Date.today, {:field_name => :report_selected_year, :start_year => current_year - 3, :end_year => current_year}, {:onchange => "Reports.barChart('Euthanasia Monthly Total By Type', 'euthanasia_monthly_total_by_type', 'Euthanized');"})%>
		</div>
	</div>
	<div class="page_content">
		<div id="euthanasia_monthly_total_by_type" class="report"></div>
	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>

app/views/reports/index.html.erb
<%= title "Reports"  %>

<%= content_for :javascripts do %>
	<script type="text/javascript">
		$(function() {
			Reports.initialize();
		});
	</script>
<% end %>

<%= content_for :page_content do %>

	<div class="page_heading blue">
		<h1>Reports</h1>
	</div>

  <div class="page_content">
    <h2>Current Active Totals</h2>
    <table class="status_counts">
      <tr>
        <th>Status</th>
        <th>Total <%= image_tag "icon_help.png", :class =>"tooltip_on_top", "data-tip" => "Current totals of active animals." %></th>
      </tr>
      <% @current_counts.each do |current_count|  %>
        <tr class="<%= cycle("odd", "even")%>">
          <td class="status"><%= current_count.name %></td>
          <td class="center"><%= current_count.count %></td>
        </tr>
      <% end %>
    </table>

    <h2>Animal Yearly Totals by Status</h2>
    <table class="status_counts">
      <tr>
        <th>Status</th>
        <th>Total <%= image_tag "icon_help.png", :class =>"tooltip_on_top", "data-tip" => "Lifetime totals. Includes previous years not displayed (if they exist.)" %></th>
        <th><%= Time.zone.today.year %></th>
        <th><%= Time.zone.today.year - 1 %></th>
        <th><%= Time.zone.today.year - 2 %></th>
        <th><%= Time.zone.today.year - 3 %></th>
      </tr>
			<% @status_counts.each do |status_history|  %>
				<tr class="<%= cycle("odd", "even")%>">
					<td class="status"><%= status_history["Status"] %></td>
					<td class="center"><%= status_history["Total"] %></td>
					<td class="center"><%= status_history[Time.zone.today.year] %></td>
					<td class="center"><%= status_history[Time.zone.today.year - 1] %></td>
          <td class="center"><%= status_history[Time.zone.today.year - 2] %></td>
          <td class="center"><%= status_history[Time.zone.today.year - 3] %></td>
				</tr>
      <% end %>
    </table>


    <div class="stats">
			<h2>Monthly Totals</h2>

      <div class="filters">
        <span class="left">
          <%= label_tag :selected_month, "Select month:" %>
          <%= select_month(Time.zone.today, :field_name => :selected_month, :prefix => "", :start_month => Time.zone.today.month )%>
        </span>
        <span class="leftPadded">
          <%= label_tag :selected_year, "Select year:" %>
          <%= select_year(Time.zone.today, :field_name => :selected_year, :prefix => "", :start_year => Time.zone.today.year - 3, :end_year => Time.zone.today.year)%>
        </span>
        <span class="leftPadded">
          <%= submit_tag "Go", :disable_with => '...', :id => "submit_report" %>
        </span>
      </div>
    </div>

		<div id="status_by_month_year" class="report"></div>
		<div class="separator"></div>
		<div id="type_by_month_year"class="report"></div>
	</div>

<% end %>

<%= content_for :sidebar do %>
	<%= render "sidebar" %>
<% end %>